[package]
name = "useful_macros"
version = "0.1.0"
edition = "2021"
description = "My useful macros"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc_macros = { path="../proc_macros", version="0.1.0" }

